PREFIX  rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
# SPARQL 1.1
SELECT *
WHERE
{	?p rdf:type ?type .
	FILTER NOT EXISTS {
		?p owl:sameAs ?same
	}
} LIMIT 100

