package org.ends.ui.server;

import org.ends.ui.client.exception.EndsException;
import org.ends.ui.client.objects.GeneralInfo;
import org.ends.ui.client.service.EndsService;

import com.google.gwt.user.server.rpc.RemoteServiceServlet;

public class EndsServiceImpl extends RemoteServiceServlet implements EndsService {
	
	public GeneralInfo loadGeneralInfo() throws EndsException{
		//TODO implement this method
		GeneralInfo generalInfo = new GeneralInfo();
		generalInfo.setTitle("SPARQL Endpoints Status&nbsp;<span><a href='http://datahub.io/' target='_blank'>> Datahub.io</a></span>");
		generalInfo.setDescription("<p>Public SPARQL endpoints list is fetch dynamically using CKAN SPARQL Endpoint.</p>"+
									"<p>Your endpoint is not in this list? Please consider adding it to the relevant package in CKAN.</p>"+
									"<p>You can query all data generated by this tool via our SPARQL endpoint.</p>"+
									"<p>Official Stats are avaialable and will be regularly published.</p>");
		generalInfo.setLastUpdateDate("2013-07-25T09:30:10+01:00");
		
		return generalInfo;
	}
	
	
}
