package org.ends.ui.server;

import org.ends.ui.client.exception.EndsException;
import org.ends.ui.client.objects.GeneralInfo;
import org.ends.ui.client.service.EndsService;

import com.google.gwt.user.server.rpc.RemoteServiceServlet;

public class EndsServiceImpl extends RemoteServiceServlet implements EndsService {
	
	public GeneralInfo loadGeneralInfo() throws EndsException{
		//TODO implement this method
		GeneralInfo generalInfo = new GeneralInfo();
		generalInfo.setTitle("- For <a href='http://datahub.io/' target='_blank'>Datahub.io</a> -");
		generalInfo.setDescription("<div>Public SPARQL endpoints list is fetch dynamically using <a target='_blank' href='http://semantic.ckan.net/sparql'>CKAN SPARQL Endpoint.</a></div>"+
				"<div style='margin-top:10px;'>Your endpoint is not in this list? Please consider adding it to the relevant package in <a href='http://ckan.net/' target='_blank'>CKAN</a>.</div>"+
				"<div style='margin-top:10px;'>You can query all data generated by this tool via our <a href='./endpoint/endpoint.html'>SPARQL endpoint</a>.</div>"+
				"<div style='margin-top:10px;'>");
		
		
		return generalInfo;
	}
	
	
}
