/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package core.discovery;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class DResult extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DResult\",\"namespace\":\"core.discovery\",\"fields\":[{\"name\":\"endpointResult\",\"type\":{\"type\":\"record\",\"name\":\"EndpointResult\",\"namespace\":\"core\",\"fields\":[{\"name\":\"endpoint\",\"type\":{\"type\":\"record\",\"name\":\"Endpoint\",\"fields\":[{\"name\":\"uri\",\"type\":\"string\"}]}},{\"name\":\"start\",\"type\":\"long\"},{\"name\":\"end\",\"type\":\"long\"}],\"imports\":[\"Endpoint.avsc\"]}},{\"name\":\"GetResult\",\"type\":{\"type\":\"record\",\"name\":\"GetResult\",\"fields\":[{\"name\":\"ResponseType\",\"type\":\"string\"},{\"name\":\"ResponseCode\",\"type\":\"string\"},{\"name\":\"ResponseServer\",\"type\":\"string\"},{\"name\":\"ResponseLink\",\"type\":\"string\"},{\"name\":\"SPARQLDESCterms\",\"type\":\"long\"},{\"name\":\"Exception\",\"type\":[\"string\",\"null\"]},{\"name\":\"VOIDterms\",\"type\":\"long\"},{\"name\":\"SPARQLDESCpreds\",\"type\":{\"type\":\"map\",\"values\":[\"string\",\"long\"]}},{\"name\":\"voiDpreds\",\"type\":{\"type\":\"map\",\"values\":[\"string\",\"long\"]}}]}},{\"name\":\"VoidResult\",\"type\":{\"type\":\"record\",\"name\":\"VoidResult\",\"fields\":[{\"name\":\"voidFile\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"Exception\",\"type\":[\"string\",\"null\"]}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public core.EndpointResult endpointResult;
  @Deprecated public core.discovery.GetResult GetResult;
  @Deprecated public core.discovery.VoidResult VoidResult;

  /**
   * Default constructor.
   */
  public DResult() {}

  /**
   * All-args constructor.
   */
  public DResult(core.EndpointResult endpointResult, core.discovery.GetResult GetResult, core.discovery.VoidResult VoidResult) {
    this.endpointResult = endpointResult;
    this.GetResult = GetResult;
    this.VoidResult = VoidResult;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return endpointResult;
    case 1: return GetResult;
    case 2: return VoidResult;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: endpointResult = (core.EndpointResult)value$; break;
    case 1: GetResult = (core.discovery.GetResult)value$; break;
    case 2: VoidResult = (core.discovery.VoidResult)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'endpointResult' field.
   */
  public core.EndpointResult getEndpointResult() {
    return endpointResult;
  }

  /**
   * Sets the value of the 'endpointResult' field.
   * @param value the value to set.
   */
  public void setEndpointResult(core.EndpointResult value) {
    this.endpointResult = value;
  }

  /**
   * Gets the value of the 'GetResult' field.
   */
  public core.discovery.GetResult getGetResult() {
    return GetResult;
  }

  /**
   * Sets the value of the 'GetResult' field.
   * @param value the value to set.
   */
  public void setGetResult(core.discovery.GetResult value) {
    this.GetResult = value;
  }

  /**
   * Gets the value of the 'VoidResult' field.
   */
  public core.discovery.VoidResult getVoidResult() {
    return VoidResult;
  }

  /**
   * Sets the value of the 'VoidResult' field.
   * @param value the value to set.
   */
  public void setVoidResult(core.discovery.VoidResult value) {
    this.VoidResult = value;
  }

  /** Creates a new DResult RecordBuilder */
  public static core.discovery.DResult.Builder newBuilder() {
    return new core.discovery.DResult.Builder();
  }
  
  /** Creates a new DResult RecordBuilder by copying an existing Builder */
  public static core.discovery.DResult.Builder newBuilder(core.discovery.DResult.Builder other) {
    return new core.discovery.DResult.Builder(other);
  }
  
  /** Creates a new DResult RecordBuilder by copying an existing DResult instance */
  public static core.discovery.DResult.Builder newBuilder(core.discovery.DResult other) {
    return new core.discovery.DResult.Builder(other);
  }
  
  /**
   * RecordBuilder for DResult instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DResult>
    implements org.apache.avro.data.RecordBuilder<DResult> {

    private core.EndpointResult endpointResult;
    private core.discovery.GetResult GetResult;
    private core.discovery.VoidResult VoidResult;

    /** Creates a new Builder */
    private Builder() {
      super(core.discovery.DResult.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(core.discovery.DResult.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing DResult instance */
    private Builder(core.discovery.DResult other) {
            super(core.discovery.DResult.SCHEMA$);
      if (isValidValue(fields()[0], other.endpointResult)) {
        this.endpointResult = data().deepCopy(fields()[0].schema(), other.endpointResult);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.GetResult)) {
        this.GetResult = data().deepCopy(fields()[1].schema(), other.GetResult);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.VoidResult)) {
        this.VoidResult = data().deepCopy(fields()[2].schema(), other.VoidResult);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'endpointResult' field */
    public core.EndpointResult getEndpointResult() {
      return endpointResult;
    }
    
    /** Sets the value of the 'endpointResult' field */
    public core.discovery.DResult.Builder setEndpointResult(core.EndpointResult value) {
      validate(fields()[0], value);
      this.endpointResult = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'endpointResult' field has been set */
    public boolean hasEndpointResult() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'endpointResult' field */
    public core.discovery.DResult.Builder clearEndpointResult() {
      endpointResult = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'GetResult' field */
    public core.discovery.GetResult getGetResult() {
      return GetResult;
    }
    
    /** Sets the value of the 'GetResult' field */
    public core.discovery.DResult.Builder setGetResult(core.discovery.GetResult value) {
      validate(fields()[1], value);
      this.GetResult = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'GetResult' field has been set */
    public boolean hasGetResult() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'GetResult' field */
    public core.discovery.DResult.Builder clearGetResult() {
      GetResult = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'VoidResult' field */
    public core.discovery.VoidResult getVoidResult() {
      return VoidResult;
    }
    
    /** Sets the value of the 'VoidResult' field */
    public core.discovery.DResult.Builder setVoidResult(core.discovery.VoidResult value) {
      validate(fields()[2], value);
      this.VoidResult = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'VoidResult' field has been set */
    public boolean hasVoidResult() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'VoidResult' field */
    public core.discovery.DResult.Builder clearVoidResult() {
      VoidResult = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public DResult build() {
      try {
        DResult record = new DResult();
        record.endpointResult = fieldSetFlags()[0] ? this.endpointResult : (core.EndpointResult) defaultValue(fields()[0]);
        record.GetResult = fieldSetFlags()[1] ? this.GetResult : (core.discovery.GetResult) defaultValue(fields()[1]);
        record.VoidResult = fieldSetFlags()[2] ? this.VoidResult : (core.discovery.VoidResult) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
