/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package sparqles.analytics.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class EPViewInteroperabilityData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EPViewInteroperabilityData\",\"namespace\":\"sparqles.analytics.avro\",\"fields\":[{\"name\":\"label\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"boolean\"},{\"name\":\"exception\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence label;
  @Deprecated public boolean value;
  @Deprecated public java.lang.CharSequence exception;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public EPViewInteroperabilityData() {}

  /**
   * All-args constructor.
   */
  public EPViewInteroperabilityData(java.lang.CharSequence label, java.lang.Boolean value, java.lang.CharSequence exception) {
    this.label = label;
    this.value = value;
    this.exception = exception;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return label;
    case 1: return value;
    case 2: return exception;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: label = (java.lang.CharSequence)value$; break;
    case 1: value = (java.lang.Boolean)value$; break;
    case 2: exception = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'label' field.
   */
  public java.lang.CharSequence getLabel() {
    return label;
  }

  /**
   * Sets the value of the 'label' field.
   * @param value the value to set.
   */
  public void setLabel(java.lang.CharSequence value) {
    this.label = value;
  }

  /**
   * Gets the value of the 'value' field.
   */
  public java.lang.Boolean getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.Boolean value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'exception' field.
   */
  public java.lang.CharSequence getException() {
    return exception;
  }

  /**
   * Sets the value of the 'exception' field.
   * @param value the value to set.
   */
  public void setException(java.lang.CharSequence value) {
    this.exception = value;
  }

  /** Creates a new EPViewInteroperabilityData RecordBuilder */
  public static sparqles.analytics.avro.EPViewInteroperabilityData.Builder newBuilder() {
    return new sparqles.analytics.avro.EPViewInteroperabilityData.Builder();
  }
  
  /** Creates a new EPViewInteroperabilityData RecordBuilder by copying an existing Builder */
  public static sparqles.analytics.avro.EPViewInteroperabilityData.Builder newBuilder(sparqles.analytics.avro.EPViewInteroperabilityData.Builder other) {
    return new sparqles.analytics.avro.EPViewInteroperabilityData.Builder(other);
  }
  
  /** Creates a new EPViewInteroperabilityData RecordBuilder by copying an existing EPViewInteroperabilityData instance */
  public static sparqles.analytics.avro.EPViewInteroperabilityData.Builder newBuilder(sparqles.analytics.avro.EPViewInteroperabilityData other) {
    return new sparqles.analytics.avro.EPViewInteroperabilityData.Builder(other);
  }
  
  /**
   * RecordBuilder for EPViewInteroperabilityData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EPViewInteroperabilityData>
    implements org.apache.avro.data.RecordBuilder<EPViewInteroperabilityData> {

    private java.lang.CharSequence label;
    private boolean value;
    private java.lang.CharSequence exception;

    /** Creates a new Builder */
    private Builder() {
      super(sparqles.analytics.avro.EPViewInteroperabilityData.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(sparqles.analytics.avro.EPViewInteroperabilityData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.label)) {
        this.label = data().deepCopy(fields()[0].schema(), other.label);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.exception)) {
        this.exception = data().deepCopy(fields()[2].schema(), other.exception);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing EPViewInteroperabilityData instance */
    private Builder(sparqles.analytics.avro.EPViewInteroperabilityData other) {
            super(sparqles.analytics.avro.EPViewInteroperabilityData.SCHEMA$);
      if (isValidValue(fields()[0], other.label)) {
        this.label = data().deepCopy(fields()[0].schema(), other.label);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.exception)) {
        this.exception = data().deepCopy(fields()[2].schema(), other.exception);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'label' field */
    public java.lang.CharSequence getLabel() {
      return label;
    }
    
    /** Sets the value of the 'label' field */
    public sparqles.analytics.avro.EPViewInteroperabilityData.Builder setLabel(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.label = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'label' field has been set */
    public boolean hasLabel() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'label' field */
    public sparqles.analytics.avro.EPViewInteroperabilityData.Builder clearLabel() {
      label = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'value' field */
    public java.lang.Boolean getValue() {
      return value;
    }
    
    /** Sets the value of the 'value' field */
    public sparqles.analytics.avro.EPViewInteroperabilityData.Builder setValue(boolean value) {
      validate(fields()[1], value);
      this.value = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'value' field has been set */
    public boolean hasValue() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'value' field */
    public sparqles.analytics.avro.EPViewInteroperabilityData.Builder clearValue() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'exception' field */
    public java.lang.CharSequence getException() {
      return exception;
    }
    
    /** Sets the value of the 'exception' field */
    public sparqles.analytics.avro.EPViewInteroperabilityData.Builder setException(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.exception = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'exception' field has been set */
    public boolean hasException() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'exception' field */
    public sparqles.analytics.avro.EPViewInteroperabilityData.Builder clearException() {
      exception = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public EPViewInteroperabilityData build() {
      try {
        EPViewInteroperabilityData record = new EPViewInteroperabilityData();
        record.label = fieldSetFlags()[0] ? this.label : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.value = fieldSetFlags()[1] ? this.value : (java.lang.Boolean) defaultValue(fields()[1]);
        record.exception = fieldSetFlags()[2] ? this.exception : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
