/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package sparqles.analytics.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class IndexAvailabilityData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"IndexAvailabilityData\",\"namespace\":\"sparqles.analytics.avro\",\"fields\":[{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"IndexAvailabilityDataPoint\",\"fields\":[{\"name\":\"x\",\"type\":\"long\"},{\"name\":\"y\",\"type\":\"double\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence key;
  @Deprecated public java.util.List<sparqles.analytics.avro.IndexAvailabilityDataPoint> values;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public IndexAvailabilityData() {}

  /**
   * All-args constructor.
   */
  public IndexAvailabilityData(java.lang.CharSequence key, java.util.List<sparqles.analytics.avro.IndexAvailabilityDataPoint> values) {
    this.key = key;
    this.values = values;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return key;
    case 1: return values;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: key = (java.lang.CharSequence)value$; break;
    case 1: values = (java.util.List<sparqles.analytics.avro.IndexAvailabilityDataPoint>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'key' field.
   */
  public java.lang.CharSequence getKey() {
    return key;
  }

  /**
   * Sets the value of the 'key' field.
   * @param value the value to set.
   */
  public void setKey(java.lang.CharSequence value) {
    this.key = value;
  }

  /**
   * Gets the value of the 'values' field.
   */
  public java.util.List<sparqles.analytics.avro.IndexAvailabilityDataPoint> getValues() {
    return values;
  }

  /**
   * Sets the value of the 'values' field.
   * @param value the value to set.
   */
  public void setValues(java.util.List<sparqles.analytics.avro.IndexAvailabilityDataPoint> value) {
    this.values = value;
  }

  /** Creates a new IndexAvailabilityData RecordBuilder */
  public static sparqles.analytics.avro.IndexAvailabilityData.Builder newBuilder() {
    return new sparqles.analytics.avro.IndexAvailabilityData.Builder();
  }
  
  /** Creates a new IndexAvailabilityData RecordBuilder by copying an existing Builder */
  public static sparqles.analytics.avro.IndexAvailabilityData.Builder newBuilder(sparqles.analytics.avro.IndexAvailabilityData.Builder other) {
    return new sparqles.analytics.avro.IndexAvailabilityData.Builder(other);
  }
  
  /** Creates a new IndexAvailabilityData RecordBuilder by copying an existing IndexAvailabilityData instance */
  public static sparqles.analytics.avro.IndexAvailabilityData.Builder newBuilder(sparqles.analytics.avro.IndexAvailabilityData other) {
    return new sparqles.analytics.avro.IndexAvailabilityData.Builder(other);
  }
  
  /**
   * RecordBuilder for IndexAvailabilityData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<IndexAvailabilityData>
    implements org.apache.avro.data.RecordBuilder<IndexAvailabilityData> {

    private java.lang.CharSequence key;
    private java.util.List<sparqles.analytics.avro.IndexAvailabilityDataPoint> values;

    /** Creates a new Builder */
    private Builder() {
      super(sparqles.analytics.avro.IndexAvailabilityData.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(sparqles.analytics.avro.IndexAvailabilityData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.key)) {
        this.key = data().deepCopy(fields()[0].schema(), other.key);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.values)) {
        this.values = data().deepCopy(fields()[1].schema(), other.values);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing IndexAvailabilityData instance */
    private Builder(sparqles.analytics.avro.IndexAvailabilityData other) {
            super(sparqles.analytics.avro.IndexAvailabilityData.SCHEMA$);
      if (isValidValue(fields()[0], other.key)) {
        this.key = data().deepCopy(fields()[0].schema(), other.key);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.values)) {
        this.values = data().deepCopy(fields()[1].schema(), other.values);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'key' field */
    public java.lang.CharSequence getKey() {
      return key;
    }
    
    /** Sets the value of the 'key' field */
    public sparqles.analytics.avro.IndexAvailabilityData.Builder setKey(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.key = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'key' field has been set */
    public boolean hasKey() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'key' field */
    public sparqles.analytics.avro.IndexAvailabilityData.Builder clearKey() {
      key = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'values' field */
    public java.util.List<sparqles.analytics.avro.IndexAvailabilityDataPoint> getValues() {
      return values;
    }
    
    /** Sets the value of the 'values' field */
    public sparqles.analytics.avro.IndexAvailabilityData.Builder setValues(java.util.List<sparqles.analytics.avro.IndexAvailabilityDataPoint> value) {
      validate(fields()[1], value);
      this.values = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'values' field has been set */
    public boolean hasValues() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'values' field */
    public sparqles.analytics.avro.IndexAvailabilityData.Builder clearValues() {
      values = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public IndexAvailabilityData build() {
      try {
        IndexAvailabilityData record = new IndexAvailabilityData();
        record.key = fieldSetFlags()[0] ? this.key : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.values = fieldSetFlags()[1] ? this.values : (java.util.List<sparqles.analytics.avro.IndexAvailabilityDataPoint>) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
