/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package core;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Endpoint extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Endpoint\",\"namespace\":\"core\",\"fields\":[{\"name\":\"uri\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence uri;

  /**
   * Default constructor.
   */
  public Endpoint() {}

  /**
   * All-args constructor.
   */
  public Endpoint(java.lang.CharSequence uri) {
    this.uri = uri;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return uri;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: uri = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'uri' field.
   */
  public java.lang.CharSequence getUri() {
    return uri;
  }

  /**
   * Sets the value of the 'uri' field.
   * @param value the value to set.
   */
  public void setUri(java.lang.CharSequence value) {
    this.uri = value;
  }

  /** Creates a new Endpoint RecordBuilder */
  public static core.Endpoint.Builder newBuilder() {
    return new core.Endpoint.Builder();
  }
  
  /** Creates a new Endpoint RecordBuilder by copying an existing Builder */
  public static core.Endpoint.Builder newBuilder(core.Endpoint.Builder other) {
    return new core.Endpoint.Builder(other);
  }
  
  /** Creates a new Endpoint RecordBuilder by copying an existing Endpoint instance */
  public static core.Endpoint.Builder newBuilder(core.Endpoint other) {
    return new core.Endpoint.Builder(other);
  }
  
  /**
   * RecordBuilder for Endpoint instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Endpoint>
    implements org.apache.avro.data.RecordBuilder<Endpoint> {

    private java.lang.CharSequence uri;

    /** Creates a new Builder */
    private Builder() {
      super(core.Endpoint.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(core.Endpoint.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Endpoint instance */
    private Builder(core.Endpoint other) {
            super(core.Endpoint.SCHEMA$);
      if (isValidValue(fields()[0], other.uri)) {
        this.uri = data().deepCopy(fields()[0].schema(), other.uri);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'uri' field */
    public java.lang.CharSequence getUri() {
      return uri;
    }
    
    /** Sets the value of the 'uri' field */
    public core.Endpoint.Builder setUri(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.uri = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'uri' field has been set */
    public boolean hasUri() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'uri' field */
    public core.Endpoint.Builder clearUri() {
      uri = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public Endpoint build() {
      try {
        Endpoint record = new Endpoint();
        record.uri = fieldSetFlags()[0] ? this.uri : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
