/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package sparqles.avro.analytics;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class IndexViewInteroperability extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"IndexViewInteroperability\",\"namespace\":\"sparqles.avro.analytics\",\"fields\":[{\"name\":\"data\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"IndexViewInterData\",\"fields\":[{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"color\",\"type\":\"string\"},{\"name\":\"data\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"IndexViewInterDataValues\",\"fields\":[{\"name\":\"label\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"double\"}]}}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<sparqles.avro.analytics.IndexViewInterData> data;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public IndexViewInteroperability() {}

  /**
   * All-args constructor.
   */
  public IndexViewInteroperability(java.util.List<sparqles.avro.analytics.IndexViewInterData> data) {
    this.data = data;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return data;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: data = (java.util.List<sparqles.avro.analytics.IndexViewInterData>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'data' field.
   */
  public java.util.List<sparqles.avro.analytics.IndexViewInterData> getData() {
    return data;
  }

  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(java.util.List<sparqles.avro.analytics.IndexViewInterData> value) {
    this.data = value;
  }

  /** Creates a new IndexViewInteroperability RecordBuilder */
  public static sparqles.avro.analytics.IndexViewInteroperability.Builder newBuilder() {
    return new sparqles.avro.analytics.IndexViewInteroperability.Builder();
  }
  
  /** Creates a new IndexViewInteroperability RecordBuilder by copying an existing Builder */
  public static sparqles.avro.analytics.IndexViewInteroperability.Builder newBuilder(sparqles.avro.analytics.IndexViewInteroperability.Builder other) {
    return new sparqles.avro.analytics.IndexViewInteroperability.Builder(other);
  }
  
  /** Creates a new IndexViewInteroperability RecordBuilder by copying an existing IndexViewInteroperability instance */
  public static sparqles.avro.analytics.IndexViewInteroperability.Builder newBuilder(sparqles.avro.analytics.IndexViewInteroperability other) {
    return new sparqles.avro.analytics.IndexViewInteroperability.Builder(other);
  }
  
  /**
   * RecordBuilder for IndexViewInteroperability instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<IndexViewInteroperability>
    implements org.apache.avro.data.RecordBuilder<IndexViewInteroperability> {

    private java.util.List<sparqles.avro.analytics.IndexViewInterData> data;

    /** Creates a new Builder */
    private Builder() {
      super(sparqles.avro.analytics.IndexViewInteroperability.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(sparqles.avro.analytics.IndexViewInteroperability.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.data)) {
        this.data = data().deepCopy(fields()[0].schema(), other.data);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing IndexViewInteroperability instance */
    private Builder(sparqles.avro.analytics.IndexViewInteroperability other) {
            super(sparqles.avro.analytics.IndexViewInteroperability.SCHEMA$);
      if (isValidValue(fields()[0], other.data)) {
        this.data = data().deepCopy(fields()[0].schema(), other.data);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'data' field */
    public java.util.List<sparqles.avro.analytics.IndexViewInterData> getData() {
      return data;
    }
    
    /** Sets the value of the 'data' field */
    public sparqles.avro.analytics.IndexViewInteroperability.Builder setData(java.util.List<sparqles.avro.analytics.IndexViewInterData> value) {
      validate(fields()[0], value);
      this.data = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'data' field has been set */
    public boolean hasData() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'data' field */
    public sparqles.avro.analytics.IndexViewInteroperability.Builder clearData() {
      data = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public IndexViewInteroperability build() {
      try {
        IndexViewInteroperability record = new IndexViewInteroperability();
        record.data = fieldSetFlags()[0] ? this.data : (java.util.List<sparqles.avro.analytics.IndexViewInterData>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
