/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package sparqles.avro.analytics;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class IndexAvailabilityDataPoint extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"IndexAvailabilityDataPoint\",\"namespace\":\"sparqles.avro.analytics\",\"fields\":[{\"name\":\"x\",\"type\":\"string\"},{\"name\":\"y\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence x;
  @Deprecated public double y;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public IndexAvailabilityDataPoint() {}

  /**
   * All-args constructor.
   */
  public IndexAvailabilityDataPoint(java.lang.CharSequence x, java.lang.Double y) {
    this.x = x;
    this.y = y;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return x;
    case 1: return y;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: x = (java.lang.CharSequence)value$; break;
    case 1: y = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'x' field.
   */
  public java.lang.CharSequence getX() {
    return x;
  }

  /**
   * Sets the value of the 'x' field.
   * @param value the value to set.
   */
  public void setX(java.lang.CharSequence value) {
    this.x = value;
  }

  /**
   * Gets the value of the 'y' field.
   */
  public java.lang.Double getY() {
    return y;
  }

  /**
   * Sets the value of the 'y' field.
   * @param value the value to set.
   */
  public void setY(java.lang.Double value) {
    this.y = value;
  }

  /** Creates a new IndexAvailabilityDataPoint RecordBuilder */
  public static sparqles.avro.analytics.IndexAvailabilityDataPoint.Builder newBuilder() {
    return new sparqles.avro.analytics.IndexAvailabilityDataPoint.Builder();
  }
  
  /** Creates a new IndexAvailabilityDataPoint RecordBuilder by copying an existing Builder */
  public static sparqles.avro.analytics.IndexAvailabilityDataPoint.Builder newBuilder(sparqles.avro.analytics.IndexAvailabilityDataPoint.Builder other) {
    return new sparqles.avro.analytics.IndexAvailabilityDataPoint.Builder(other);
  }
  
  /** Creates a new IndexAvailabilityDataPoint RecordBuilder by copying an existing IndexAvailabilityDataPoint instance */
  public static sparqles.avro.analytics.IndexAvailabilityDataPoint.Builder newBuilder(sparqles.avro.analytics.IndexAvailabilityDataPoint other) {
    return new sparqles.avro.analytics.IndexAvailabilityDataPoint.Builder(other);
  }
  
  /**
   * RecordBuilder for IndexAvailabilityDataPoint instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<IndexAvailabilityDataPoint>
    implements org.apache.avro.data.RecordBuilder<IndexAvailabilityDataPoint> {

    private java.lang.CharSequence x;
    private double y;

    /** Creates a new Builder */
    private Builder() {
      super(sparqles.avro.analytics.IndexAvailabilityDataPoint.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(sparqles.avro.analytics.IndexAvailabilityDataPoint.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.x)) {
        this.x = data().deepCopy(fields()[0].schema(), other.x);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.y)) {
        this.y = data().deepCopy(fields()[1].schema(), other.y);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing IndexAvailabilityDataPoint instance */
    private Builder(sparqles.avro.analytics.IndexAvailabilityDataPoint other) {
            super(sparqles.avro.analytics.IndexAvailabilityDataPoint.SCHEMA$);
      if (isValidValue(fields()[0], other.x)) {
        this.x = data().deepCopy(fields()[0].schema(), other.x);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.y)) {
        this.y = data().deepCopy(fields()[1].schema(), other.y);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'x' field */
    public java.lang.CharSequence getX() {
      return x;
    }
    
    /** Sets the value of the 'x' field */
    public sparqles.avro.analytics.IndexAvailabilityDataPoint.Builder setX(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.x = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'x' field has been set */
    public boolean hasX() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'x' field */
    public sparqles.avro.analytics.IndexAvailabilityDataPoint.Builder clearX() {
      x = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'y' field */
    public java.lang.Double getY() {
      return y;
    }
    
    /** Sets the value of the 'y' field */
    public sparqles.avro.analytics.IndexAvailabilityDataPoint.Builder setY(double value) {
      validate(fields()[1], value);
      this.y = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'y' field has been set */
    public boolean hasY() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'y' field */
    public sparqles.avro.analytics.IndexAvailabilityDataPoint.Builder clearY() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public IndexAvailabilityDataPoint build() {
      try {
        IndexAvailabilityDataPoint record = new IndexAvailabilityDataPoint();
        record.x = fieldSetFlags()[0] ? this.x : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.y = fieldSetFlags()[1] ? this.y : (java.lang.Double) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
